# @file mods.toml
# @spec TOML v0.5.0 (https://github.com/toml-lang/toml)
modLoader="javafml"
loaderVersion="${version_range_loader}"
issueTrackerURL="${meta_issues}"
license="${meta_license}"

[[mods]]
modId="${meta_modid}"
version="${version_mod}"
displayName="${meta_modname}"
description='''${meta_description}'''
authors="${meta_author}"
credits=""
updateJSONURL="${meta_updateurl}"
displayURL="${meta_download}"
logoFile="logo.png"

[[dependencies.${meta_modid}]]
  modId="forge"
  mandatory=true
  versionRange="${version_range_neoforge}"
  ordering="NONE"
  side="BOTH"

[[dependencies.${meta_modid}]]
  modId="minecraft"
  mandatory=true
  versionRange="[${version_minecraft}]"
  ordering="NONE"
  side="BOTH"
